---
- name: Install the dnf copr plugin
  ansible.builtin.package:
    name: "{{ caddy_copr_plugin_package }}"
    state: present
  when: caddy_use_official_repo

- name: Enable the official Caddy COPR repository
  community.general.copr:
    name: "{{ caddy_copr_project }}"
    chroot: "{{ caddy_copr_chroot }}"
    state: enabled
  when: caddy_use_official_repo

- name: Install Caddy
  ansible.builtin.package:
    name: "{{ caddy_package_name }}{{ '-' + caddy_version if caddy_version | length > 0 else '' }}"
    state: "{{ 'present' if caddy_version | length > 0 else caddy_package_state }}"
